version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./.docker/data/mongo:/data/db
    ports:
      - 27017:27017
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .docker/data/elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200