version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./.docker/data/mongo:/data/db
    ports:
      - ${DB_PORT}:27017
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .docker/data/elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    image: redis
    restart: always
    volumes:
      - ./.docker/data/redis:/data
    ports:
      - ${REDIS_PORT}:6379